In [1]:
import numpy as np


A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])


stacked_vertically = np.vstack((A, B))
stacked_horizontally = np.hstack((A, B))


common_elements = np.intersect1d(A, B)

numbers_within_range = A[(A >= 5) & (A <= 10)]


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])


filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]


print("Stacked Vertically:\n", stacked_vertically)
print("Stacked Horizontally:\n", stacked_horizontally)
print("Common Elements between A and B:\n", common_elements)
print("Numbers within the range [5, 10] in A:\n", numbers_within_range)
print("Filtered Rows of iris_2d:\n", filtered_rows)


Stacked Vertically:
 [[1 2 3 4 5]
 [4 5 6 7 8]]
Stacked Horizontally:
 [1 2 3 4 5 4 5 6 7 8]
Common Elements between A and B:
 [4 5]
Numbers within the range [5, 10] in A:
 [5]
Filtered Rows of iris_2d:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [2]:

data = {'Manufacturer': ['Audi', 'BMW', 'Chevrolet', 'Ford', 'Honda', 'Hyundai'],
        'Model': ['A4', 'X5', 'Malibu', 'Mustang', 'Civic', 'Elantra'],
        'Type': ['Sedan', 'SUV', 'Sedan', 'Muscle Car', 'Sedan', 'Sedan']}
df = pd.DataFrame(data)

filtered_data = df.iloc[::20, [0, 1, 2]]

print(filtered_data)


  Manufacturer Model   Type
0         Audi    A4  Sedan


In [3]:

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Calculate the mean of 'Min.Price' and 'Max.Price' columns
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()


df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)


print(df)


   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [4]:
import pandas as pd
import numpy as np

# Create a DataFrame with random integer values
data = np.random.randint(10, 40, 60).reshape(-1, 4)
df = pd.DataFrame(data)

# Calculate the row sums and filter rows with sum > 100
row_sums = df.sum(axis=1)
result = df[row_sums > 100]

# Print the rows with row sum > 100
print(result)


     0   1   2   3
3   10  36  38  33
6   34  27  22  38
9   15  29  26  38
12  13  29  31  33
